// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#define BaseStream_ReadWriteHandleID_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: BaseStream_ReadWriteHandleID_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::BaseStream::ReadWriteHandleID\")")
#define CBaseRTTIType_VFT_Addr 0x2F87400
#define CBaseRTTIType_dstr_Addr                                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CBaseRTTIType_dstr_Addr"                             \
              "is 0 - Zoltan found no matches for RED4ext::CBaseRTTIType_dstr\")")
#define CClass_AddEventCallbackType_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CClass_AddEventCallbackType_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::CClass::AddEventCallbackType\")")
#define CClass_ApplyFlags_Addr 0x99FC7C
#define CClass_SetupScriptCallbacks_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CClass_SetupScriptCallbacks_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::CClass::SetupScriptCallbacks\")")
#define CClass_VFT_Addr 0x3D640
#define CGameFramework_Systems_120_128_130_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CGameFramework_Systems_120_128_130_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::CGameFramework::Systems_120_128_130\")")
#define CRTTIArrayType_VFT_Addr 0x2A8E070
#define CRTTIHandleType_VFT_Addr 0x2A8DE90
#define CRTTINativeArrayType_VFT_Addr 0x2A94A28
#define CRTTIPointerType_VFT_Addr 0x2A72D60
#define CRTTIResourceAsyncReferenceType_VFT_Addr 0x2AEFFF0
#define CRTTIResourceReferenceType_VFT_Addr 0x2B04698
#define CRTTIStaticArrayType_VFT_Addr 0x2A94570
#define CRTTIWeakHandleType_VFT_Addr 0x2A8DF80
#define CallbackManager_AddCallback_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CallbackManager_AddCallback_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::CallbackManager::AddCallback\")")
#define CallbackManager_AddToUnk00_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CallbackManager_AddToUnk00_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::CallbackManager::AddToUnk00\")")
#define CallbackManager_Unknown1_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CallbackManager_Unknown1_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::CallbackManager::Unknown1\")")
#define CallbackManager_Unknown6_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CallbackManager_Unknown6_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::CallbackManager::Unknown6\")")
#define GameInstance_GameInstance_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameInstance_GameInstance_Addr"                      \
              "is 0 - Zoltan found no matches for RED4ext::GameInstance::GameInstance\")")
#define GameInstance_SetRuntimeScene_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameInstance_SetRuntimeScene_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::GameInstance::SetRuntimeScene\")")
#define GameOptionManager_Get_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameOptionManager_Get_Addr"                          \
              "is 0 - Zoltan found no matches for RED4ext::GameOptionManager::Get\")")
#define GameOptionManager_GetGameOption_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameOptionManager_GetGameOption_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::GameOptionManager::GetGameOption\")")
#define GameOptionManager_SetGameOption_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameOptionManager_SetGameOption_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::GameOptionManager::SetGameOption\")")
#define GetGameSystemsData_Addr                                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GetGameSystemsData_Addr"                             \
              "is 0 - Zoltan found no matches for RED4ext::GetGameSystemsData\")")
#define IDynamicStorage_IDynamicStorage_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IDynamicStorage_IDynamicStorage_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::IDynamicStorage::IDynamicStorage\")")
#define IGameInstance_RegisterGameLoadCallbacks_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_RegisterGameLoadCallbacks_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::RegisterGameLoadCallbacks\")")
#define IGameInstance_RegisterStreamingWorldLoadedCallback_Addr                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_RegisterStreamingWorldLoadedCallback_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::RegisterStreamingWorldLoadedCallback\")")
#define IGameInstance_Systems158_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_Systems158_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::Systems158\")")
#define IGameInstance_Systems160_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_Systems160_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::Systems160\")")
#define IGameInstance_Systems168o170_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_Systems168o170_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::Systems168o170\")")
#define IGameInstance_Systems178_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_Systems178_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::Systems178\")")
#define IGameInstance_WorldDetached_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_WorldDetached_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::WorldDetached\")")
#define IGameInstance_WorldPendingDetach_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IGameInstance_WorldPendingDetach_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::IGameInstance::WorldPendingDetach\")")
#define IScriptable_VFT_Addr 0x2A47200
#define ISerializable_CLASS_Addr 0x331BF98
#define ISerializable_GetNativeType_Addr 0x18E3270
#define ISerializable_SetOwner_Addr 0x44F1B0
#define ISerializable_VFT_Addr 0x2A47100
#define LoadGameSystemsData_Addr                                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: LoadGameSystemsData_Addr"                            \
              "is 0 - Zoltan found no matches for RED4ext::LoadGameSystemsData\")")
#define PureCall_Addr                                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: PureCall_Addr"                                       \
              "is 0 - Zoltan found no matches for RED4ext::PureCall\")")
#define Return0u16_Addr 0x194CFA0
#define Return1_Addr 0xFAE880
#define Return10_Addr 0x18E3730
#define Return11_Addr 0x18E3710
#define Return12_Addr 0x18E3700
#define Return13_Addr 0x18E37C0
#define Return14_Addr 0x18E3330
#define Return15_Addr 0x18E3720
#define Return16u32_Addr 0x18E35E0
#define Return1f_Addr                                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: Return1f_Addr"                                       \
              "is 0 - Zoltan found no matches for RED4ext::Return1f\")")
#define Return1u32_Addr 0x18E36C0
#define Return2_Addr 0x18E3660
#define Return24u32_Addr 0x18E35C0
#define Return3_Addr 0x18E3780
#define Return32u32_Addr 0x18E35F0
#define Return4_Addr 0x18E3320
#define Return40u32_Addr 0x18E3610
#define Return4u32_Addr 0x18E35D0
#define Return5_Addr 0x18E3750
#define Return6_Addr 0x18E37B0
#define Return7_Addr 0x18E37A0
#define Return8_Addr 0x18E36F0
#define Return88u32_Addr 0x18E3600
#define Return8u32_Addr 0x18E32F0
#define Return9_Addr 0x18E36E0
#define ReturnN1i32_Addr 0x18E36A0
#define ReturnZero64_Addr 0x4787E0
#define ReturnZero8_Addr 0x193F420
#define UpdatableSystems_SetRuntimeScene_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdatableSystems_SetRuntimeScene_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::UpdatableSystems::SetRuntimeScene\")")
#define UpdateManagerHolder_Something_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManagerHolder_Something_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManagerHolder::Something\")")
#define UpdateManagerHolder_UpdateSystems_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManagerHolder_UpdateSystems_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManagerHolder::UpdateSystems\")")
#define UpdateManagerUpdateStorage_Copy_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManagerUpdateStorage_Copy_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManager::UpdateStorage::Copy\")")
#define UpdateManagerUpdateStorage_Copy_0_Addr 0x81E1D4
#define UpdateManagerUpdateStorage_FireCallback_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManagerUpdateStorage_FireCallback_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManager::UpdateStorage::FireCallback\")")
#define UpdateManager_IterateUnknown_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManager_IterateUnknown_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManager::IterateUnknown\")")
#define UpdateManager_PrepareFiring_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManager_PrepareFiring_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManager::PrepareFiring\")")
#define UpdateManager_RegisterUpdate_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManager_RegisterUpdate_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManager::RegisterUpdate\")")
#define UpdateManager_ReleaseUnknown_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManager_ReleaseUnknown_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManager::ReleaseUnknown\")")
#define UpdateManager_Setup_Addr                                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: UpdateManager_Setup_Addr"                            \
              "is 0 - Zoltan found no matches for RED4ext::UpdateManager::Setup\")")
#define WidgetHudComponentInterface_WidgetHudComponentInterface_Addr                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: WidgetHudComponentInterface_WidgetHudComponentInterface_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::WidgetHudComponentInterface::WidgetHudComponentInterface\")")
#define WidgetHudComponentInterface__WidgetHudComponentInterface_Addr                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: WidgetHudComponentInterface__WidgetHudComponentInterface_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::WidgetHudComponentInterface::~WidgetHudComponentInterface\")")
#define actionActionBase_Lock_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: actionActionBase_Lock_Addr"                          \
              "is 0 - Zoltan found too many matches for RED4ext::action::ActionBase::Lock (2)\")")
#define actionActionBase_StartWithReplicatedState_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: actionActionBase_StartWithReplicatedState_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::action::ActionBase::StartWithReplicatedState\")")
#define actionActionInterface_EndActions_Addr 0x2B09F0
#define actionActionInterface_IsAnimationiActive_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: actionActionInterface_IsAnimationiActive_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::action::ActionInterface::IsAnimationiActive\")")
#define actionActionInterface_ProcessActions_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: actionActionInterface_ProcessActions_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::action::ActionInterface::ProcessActions\")")
#define appearanceAppearanceDefinition_AppearanceDefinition_Addr                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: appearanceAppearanceDefinition_AppearanceDefinition_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::appearance::AppearanceDefinition::AppearanceDefinition\")")
#define audioBankManager_LoadBank_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioBankManager_LoadBank_Addr"                      \
              "is 0 - Zoltan found no matches for RED4ext::audio::BankManager::LoadBank\")")
#define audioBankManager_LoadBanksMaybe_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioBankManager_LoadBanksMaybe_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::audio::BankManager::LoadBanksMaybe\")")
#define audioBankManager_UnloadBank_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioBankManager_UnloadBank_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::audio::BankManager::UnloadBank\")")
#define audioEmitters_GetEmitterForEntityID_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioEmitters_GetEmitterForEntityID_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::audio::Emitters::GetEmitterForEntityID\")")
#define audioEmitters_GetOrCreateEmitter_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioEmitters_GetOrCreateEmitter_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::audio::Emitters::GetOrCreateEmitter\")")
#define audioGameParameterStorage_GetValue_Addr 0x35417C
#define audioGameParameterStorage_SetValue_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioGameParameterStorage_SetValue_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::audio::GameParameterStorage::SetValue\")")
#define audioMetadataManager_GetValueInMapForName_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioMetadataManager_GetValueInMapForName_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::audio::MetadataManager::GetValueInMapForName\")")
#define audioMetadataManager_MetadataManager_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioMetadataManager_MetadataManager_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::audio::MetadataManager::MetadataManager\")")
#define audioMetadataManager__MetadataManager_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioMetadataManager__MetadataManager_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::audio::MetadataManager::~MetadataManager\")")
#define audioThing_AKAudioLoad_Addr                                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioThing_AKAudioLoad_Addr"                         \
              "is 0 - Zoltan found no matches for RED4ext::audio::Thing::AKAudioLoad\")")
#define audioThing_GetEmitterPosition_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioThing_GetEmitterPosition_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::audio::Thing::GetEmitterPosition\")")
#define audioThing_UpdateEmitterPosition_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioThing_UpdateEmitterPosition_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::audio::Thing::UpdateEmitterPosition\")")
#define audioVehicleMetadata_GetEventData_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioVehicleMetadata_GetEventData_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::audio::VehicleMetadata::GetEventData\")")
#define audio_UpdateGlobalParameter_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audio_UpdateGlobalParameter_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::audio::UpdateGlobalParameter\")")
#define audio_UpdateParameterForEntityID_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audio_UpdateParameterForEntityID_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::audio::UpdateParameterForEntityID\")")
#define entAnimatedComponent_GetReferencePoseMSForName_Addr                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entAnimatedComponent_GetReferencePoseMSForName_Addr" \
              "is 0 - Zoltan found no matches for RED4ext::ent::AnimatedComponent::GetReferencePoseMSForName\")")
#define entComponentsStorage_AddComponent_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entComponentsStorage_AddComponent_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::ent::ComponentsStorage::AddComponent\")")
#define entComponentsStorage_AddComponents_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entComponentsStorage_AddComponents_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::ent::ComponentsStorage::AddComponents\")")
#define entComponentsStorage_FreeMemory_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entComponentsStorage_FreeMemory_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::ent::ComponentsStorage::FreeMemory\")")
#define entComponentsStorage_GetComponentByCRUID_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entComponentsStorage_GetComponentByCRUID_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::ent::ComponentsStorage::GetComponentByCRUID\")")
#define entComponentsStorage_GetSize_Addr 0x18E8E90
#define entComponentsStorage_IsEmpty_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entComponentsStorage_IsEmpty_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::ent::ComponentsStorage::IsEmpty\")")
#define entEntity_ReassembleAppearance_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entEntity_ReassembleAppearance_Addr"                 \
              "is 0 - Zoltan found no matches for RED4ext::ent::Entity::ReassembleAppearance\")")
#define entEntity_SetRuntime_Addr 0x1C7A160
#define entEntity_SetupEntityAndComponents_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entEntity_SetupEntityAndComponents_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::ent::Entity::SetupEntityAndComponents\")")
#define entEntity_SomethingListeners_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entEntity_SomethingListeners_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::ent::Entity::SomethingListeners\")")
#define entIAttachment_destination_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entIAttachment_destination_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::ent::IAttachment::destination\")")
#define entIComponent_InitializeReplicated_Addr 0x23809E4
#define entIComponent_SetEntity_Addr                                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entIComponent_SetEntity_Addr"                        \
              "is 0 - Zoltan found too many matches for RED4ext::ent::IComponent::SetEntity (5)\")")
#define entIComponent_VFT_Addr 0x2A49938
#define entIPlacedComponent_VFT_Addr 0x2A496E8
#define entMeshComponent_Load_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entMeshComponent_Load_Addr"                          \
              "is 0 - Zoltan found no matches for RED4ext::ent::MeshComponent::Load\")")
#define entPhysicalMeshComponent_ProcessSystemResource_Addr                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entPhysicalMeshComponent_ProcessSystemResource_Addr" \
              "is 0 - Zoltan found no matches for RED4ext::ent::PhysicalMeshComponent::ProcessSystemResource\")")
#define entSlotComponent_GetLocalSlotTransformFromIndex_Addr 0x15EC98
#define entSlotComponent_GetSlotGlobalTransform_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entSlotComponent_GetSlotGlobalTransform_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::ent::SlotComponent::GetSlotGlobalTransform\")")
#define entSlotComponent_GetSlotIndex_Addr 0x161C94
#define entSlotComponent_GetSlotLocalTransform_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entSlotComponent_GetSlotLocalTransform_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::ent::SlotComponent::GetSlotLocalTransform\")")
#define entSlotComponent_GetSlotTransform_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entSlotComponent_GetSlotTransform_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::ent::SlotComponent::GetSlotTransform\")")
#define entVisualControllerComponent_GetAppearanceDependency_Addr                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entVisualControllerComponent_GetAppearanceDependency_Addr"\
              "is 0 - Zoltan found too many matches for RED4ext::ent::VisualControllerComponent::GetAppearanceDependency (3)\")")
#define entVisualControllerComponent_LoadUnkD8_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entVisualControllerComponent_LoadUnkD8_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::ent::VisualControllerComponent::LoadUnkD8\")")
#define entVisualControllerComponent_Set0xF4_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entVisualControllerComponent_Set0xF4_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::ent::VisualControllerComponent::Set0xF4\")")
#define entVisualControllerComponent_Unknown_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entVisualControllerComponent_Unknown_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::ent::VisualControllerComponent::Unknown\")")
#define gameCActionsFactory_AddActionTypeManual_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameCActionsFactory_AddActionTypeManual_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::game::CActionsFactory::AddActionTypeManual\")")
#define gameFxEventInterface_Add_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxEventInterface_Add_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::game::FxEventInterface::Add\")")
#define gameFxInstance_IsValid_Addr                                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_IsValid_Addr"                         \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::IsValid\")")
#define gameFxInstance_QueueAttachToComponent_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_QueueAttachToComponent_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::QueueAttachToComponent\")")
#define gameFxInstance_QueueAttachToSlot_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_QueueAttachToSlot_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::QueueAttachToSlot\")")
#define gameFxInstance_QueueBreakLoop_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_QueueBreakLoop_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::QueueBreakLoop\")")
#define gameFxInstance_QueueKill_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_QueueKill_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::QueueKill\")")
#define gameFxInstance_QueueSetBlackboardValue_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_QueueSetBlackboardValue_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::QueueSetBlackboardValue\")")
#define gameFxInstance_QueueUpdateTargetPosition_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_QueueUpdateTargetPosition_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::QueueUpdateTargetPosition\")")
#define gameFxInstance_QueueUpdateTransform_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameFxInstance_QueueUpdateTransform_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::game::FxInstance::QueueUpdateTransform\")")
#define gameGameAudioSystem_SetGlobalParameter_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameGameAudioSystem_SetGlobalParameter_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::game::GameAudioSystem::SetGlobalParameter\")")
#define gameGameAudioSystem_UpdateParameter_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameGameAudioSystem_UpdateParameter_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::game::GameAudioSystem::UpdateParameter\")")
#define gameIGameSystem_GetNativeType_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameIGameSystem_GetNativeType_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::game::IGameSystem::GetNativeType\")")
#define gameIGameSystem_SetGameInstance_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameIGameSystem_SetGameInstance_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::game::IGameSystem::SetGameInstance\")")
#define gameIGameSystem_Unset_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameIGameSystem_Unset_Addr"                          \
              "is 0 - Zoltan found no matches for RED4ext::game::IGameSystem::Unset\")")
#define gameIGameSystem_VFT_Addr                                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameIGameSystem_VFT_Addr"                            \
              "is 0 - Zoltan found no matches for RED4ext::game::IGameSystem::VFT\")")
#define gameMutexable_Update_Addr                                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameMutexable_Update_Addr"                           \
              "is 0 - Zoltan found no matches for RED4ext::game::Mutexable::Update\")")
#define gameObject_CallScriptFunction_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameObject_CallScriptFunction_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::game::Object::CallScriptFunction\")")
#define gameVehicleSystem_BeginUpdate_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_BeginUpdate_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::BeginUpdate\")")
#define gameVehicleSystem_FixedUpdate_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_FixedUpdate_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::FixedUpdate\")")
#define gameVehicleSystem_FixedUpdate_PreSolve_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_FixedUpdate_PreSolve_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::FixedUpdate_PreSolve\")")
#define gameVehicleSystem_Interpolation_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_Interpolation_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::Interpolation\")")
#define gameVehicleSystem_PostMove_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_PostMove_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::PostMove\")")
#define gameVehicleSystem_PreUpdateAndPreMove_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_PreUpdateAndPreMove_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::PreUpdateAndPreMove\")")
#define gameVehicleSystem_SingleFixedStep_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_SingleFixedStep_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::SingleFixedStep\")")
#define gameVehicleSystem_UpdateVehicleArrays_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameVehicleSystem_UpdateVehicleArrays_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::game::VehicleSystem::UpdateVehicleArrays\")")
#define physicsBaseProxy_Process_Addr 0x18E5E10
#define physicsBaseProxy_VFT_Addr 0x2A6CD88
#define physicsColliderSphere_createHandleWithRadius_Addr 0x2099EE8
#define physicsGeometryCache_FreeAlwaysLoaded_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_FreeAlwaysLoaded_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::FreeAlwaysLoaded\")")
#define physicsGeometryCache_FreeGeometryKey_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_FreeGeometryKey_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::FreeGeometryKey\")")
#define physicsGeometryCache_FreeKey_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_FreeKey_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::FreeKey\")")
#define physicsGeometryCache_FreeSector_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_FreeSector_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::FreeSector\")")
#define physicsGeometryCache_HasGeometryKey_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_HasGeometryKey_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::HasGeometryKey\")")
#define physicsGeometryCache_LoadAlwaysloadedSectorGeometries_Addr                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_LoadAlwaysloadedSectorGeometries_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::LoadAlwaysloadedSectorGeometries\")")
#define physicsGeometryCache_LoadAlwaysloadedSectorGeometriesSetup_Addr                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_LoadAlwaysloadedSectorGeometriesSetup_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::LoadAlwaysloadedSectorGeometriesSetup\")")
#define physicsGeometryCache_LoadSectorGeometries_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_LoadSectorGeometries_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::LoadSectorGeometries\")")
#define physicsGeometryCache_LoadSectorGeometriesSetup_Addr                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_LoadSectorGeometriesSetup_Addr" \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::LoadSectorGeometriesSetup\")")
#define physicsGeometryCache_Unknown_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_Unknown_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::Unknown\")")
#define physicsGeometryCache_sub_7FF75B921520_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_sub_7FF75B921520_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::sub_7FF75B921520\")")
#define physicsGeometryCache_sub_7FF75B922410_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_sub_7FF75B922410_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::sub_7FF75B922410\")")
#define physicsICollider_GetNativeType_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsICollider_GetNativeType_Addr"                 \
              "is 0 - Zoltan found no matches for RED4ext::physics::ICollider::GetNativeType\")")
#define physicsICollider_VFT_Addr 0x2A6D818
#define physicsICollider_cstr_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsICollider_cstr_Addr"                          \
              "is 0 - Zoltan found no matches for RED4ext::physics::ICollider::cstr\")")
#define physicsICollider_sub_108_Addr 0x18E5C60
#define physicsProxyCacheID_DisableCollision_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyCacheID_DisableCollision_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyCacheID::DisableCollision\")")
#define physicsProxyCacheID_EnableCollision_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyCacheID_EnableCollision_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyCacheID::EnableCollision\")")
#define physicsProxyCacheManagerUnk948_Kick_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyCacheManagerUnk948_Kick_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyCacheManager::Unk948::Kick\")")
#define physicsProxyCache_AddToCache_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyCache_AddToCache_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyCache::AddToCache\")")
#define physicsProxyCache_GetDataFromCache_Addr 0x27AC5C
#define physicsProxyCache_GetFromCacheOrGet_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyCache_GetFromCacheOrGet_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyCache::GetFromCacheOrGet\")")
#define physicsProxyHelper_Create_Addr 0x27A650
#define physicsProxyHelper_GetThingWithLock_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_GetThingWithLock_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::GetThingWithLock\")")
#define physicsProxyHelper_Lock_Addr 0x27A650
#define physicsProxyHelper_SetAngularDamping_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetAngularDamping_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetAngularDamping\")")
#define physicsProxyHelper_SetCCD_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetCCD_Addr"                      \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetCCD\")")
#define physicsProxyHelper_SetCMassLocalPose_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetCMassLocalPose_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetCMassLocalPose\")")
#define physicsProxyHelper_SetGravity_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetGravity_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetGravity\")")
#define physicsProxyHelper_SetIsQueryable_Addr 0x1FDC59C
#define physicsProxyHelper_SetLinearDamping_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetLinearDamping_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetLinearDamping\")")
#define physicsProxyHelper_SetMassAndUpdateInertia_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetMassAndUpdateInertia_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetMassAndUpdateInertia\")")
#define physicsProxyHelper_SetQueryFilterData_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetQueryFilterData_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetQueryFilterData\")")
#define physicsProxyHelper_SetSimulationFilterData_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetSimulationFilterData_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::SetSimulationFilterData\")")
#define physicsProxyHelper_SetSimulationShape_Addr 0x1FDC520
#define physicsProxyHelper_Unlock_Addr 0x1DE238
#define physicsProxyHelper_UpdateGlobalPose_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_UpdateGlobalPose_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::UpdateGlobalPose\")")
#define physicsProxyHelper_UpdateProxyCache_Addr 0x27A784
#define physicsProxyID_GetEntity_Addr 0x8C4D94
#define physicsProxyID_GetKeyUnk37_0x40_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_GetKeyUnk37_0x40_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::GetKeyUnk37_0x40\")")
#define physicsProxyID_GetNbShapes_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_GetNbShapes_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::GetNbShapes\")")
#define physicsProxyID_GetProxy_Addr                                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_GetProxy_Addr"                        \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::GetProxy\")")
#define physicsProxyID_ProcessProxyDesc_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_ProcessProxyDesc_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::ProcessProxyDesc\")")
#define physicsProxyID_Something2_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_Something2_Addr"                      \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::Something2\")")
#define physicsProxyID_Unk_Addr                                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_Unk_Addr"                             \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::Unk\")")
#define physicsProxyID_UpdateProxyCacheEntry_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_UpdateProxyCacheEntry_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::UpdateProxyCacheEntry\")")
#define physicsProxyManager_GetProxyCache_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyManager_GetProxyCache_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyManager::GetProxyCache\")")
#define physicsProxyManager_GetProxyHandle_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyManager_GetProxyHandle_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyManager::GetProxyHandle\")")
#define physicsProxyManager_HasProxy_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyManager_HasProxy_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyManager::HasProxy\")")
#define physicsProxyManager_SetProxyCacheID_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyManager_SetProxyCacheID_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyManager::SetProxyCacheID\")")
#define physicsSystemResource_GetFromCMesh_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsSystemResource_GetFromCMesh_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::physics::SystemResource::GetFromCMesh\")")
#define physicsVehiclePhysicsInsert1_ReferencePoseSetup_Addr                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsVehiclePhysicsInsert1_ReferencePoseSetup_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::physics::VehiclePhysicsInsert1::ReferencePoseSetup\")")
#define physicsVehiclePhysicsInsert1_SinMath_Addr 0x2355E4
#define physics_GetShapeLocalPos_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physics_GetShapeLocalPos_Addr"                       \
              "is 0 - Zoltan found no matches for RED4ext::physics::GetShapeLocalPos\")")
#define physics_ProxyID_GetGlobalPose_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physics_ProxyID_GetGlobalPose_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID_GetGlobalPose\")")
#define physics_proxyManager_Addr 0x33DCC50
#define physics_pxRigidBody_Get_Addr                                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physics_pxRigidBody_Get_Addr"                        \
              "is 0 - Zoltan found no matches for RED4ext::physics::pxRigidBody_Get\")")
#define physics_pxRigidBody_Update_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physics_pxRigidBody_Update_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::physics::pxRigidBody_Update\")")
#define purecall_Addr 0x1905FAC
#define rtti_Addr 0x3F2DF78
#define userRuntimeSettingsVar_RuntimeSettingsVar_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: userRuntimeSettingsVar_RuntimeSettingsVar_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::user::RuntimeSettingsVar::RuntimeSettingsVar\")")
#define user_GetSettings_Addr                                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: user_GetSettings_Addr"                               \
              "is 0 - Zoltan found no matches for RED4ext::user::GetSettings\")")
#define vehicleAcoustics_GetAudioResourceMetadata_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_GetAudioResourceMetadata_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::GetAudioResourceMetadata\")")
#define vehicleAcoustics_IsRadioReceiverActive_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_IsRadioReceiverActive_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::IsRadioReceiverActive\")")
#define vehicleAcoustics_NextRadioReceiverStation_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_NextRadioReceiverStation_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::NextRadioReceiverStation\")")
#define vehicleAcoustics_SetRadioTier_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_SetRadioTier_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::SetRadioTier\")")
#define vehicleAcoustics_ShouldUseSomeAVListener_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_ShouldUseSomeAVListener_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::ShouldUseSomeAVListener\")")
#define vehicleAcoustics_ToggleHorn_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_ToggleHorn_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::ToggleHorn\")")
#define vehicleAcoustics_Update_Addr                                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_Update_Addr"                        \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::Update\")")
#define vehicleAcoustics_Update3CA_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_Update3CA_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::Update3CA\")")
#define vehicleAcoustics_UpdateEvents_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_UpdateEvents_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::UpdateEvents\")")
#define vehicleAcoustics_UpdateTPPinAudioSystem_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_UpdateTPPinAudioSystem_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::UpdateTPPinAudioSystem\")")
#define vehicleAcoustics_UpdateTireParameters_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_UpdateTireParameters_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::UpdateTireParameters\")")
#define vehicleAcoustics_UpdateWheelEmitters_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAcoustics_UpdateWheelEmitters_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Acoustics::UpdateWheelEmitters\")")
#define vehicleAirControl_ApplyTorque_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAirControl_ApplyTorque_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::AirControl::ApplyTorque\")")
#define vehicleAirControl_GetAngularVelocity_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAirControl_GetAngularVelocity_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::AirControl::GetAngularVelocity\")")
#define vehicleAirControl_Process_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleAirControl_Process_Addr"                      \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::AirControl::Process\")")
#define vehicleBaseObject_CheckPhysicsStateActionInterface_Addr                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_CheckPhysicsStateActionInterface_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::CheckPhysicsStateActionInterface\")")
#define vehicleBaseObject_CreateAction_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_CreateAction_Addr"                 \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::CreateAction\")")
#define vehicleBaseObject_GetCurveSetData_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetCurveSetData_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetCurveSetData\")")
#define vehicleBaseObject_GetDeceleration_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetDeceleration_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetDeceleration\")")
#define vehicleBaseObject_GetDisplayName_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetDisplayName_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetDisplayName\")")
#define vehicleBaseObject_GetGravitationalForce_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetGravitationalForce_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetGravitationalForce\")")
#define vehicleBaseObject_GetInverseMass_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetInverseMass_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetInverseMass\")")
#define vehicleBaseObject_GetNativeType_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetNativeType_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetNativeType\")")
#define vehicleBaseObject_GetPhysicsData_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetPhysicsData_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetPhysicsData\")")
#define vehicleBaseObject_GetTotalMass_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetTotalMass_Addr"                 \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetTotalMass\")")
#define vehicleBaseObject_GetUnk60C_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetUnk60C_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetUnk60C\")")
#define vehicleBaseObject_GetUnk8E0_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetUnk8E0_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetUnk8E0\")")
#define vehicleBaseObject_GetVehicleSystem_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetVehicleSystem_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetVehicleSystem\")")
#define vehicleBaseObject_GetWeaponOrientation_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_GetWeaponOrientation_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::GetWeaponOrientation\")")
#define vehicleBaseObject_HornForDuration_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_HornForDuration_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::HornForDuration\")")
#define vehicleBaseObject_HornForDurationDelayed_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_HornForDurationDelayed_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::HornForDurationDelayed\")")
#define vehicleBaseObject_PostMovePhysicsStateNotZero_Addr                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_PostMovePhysicsStateNotZero_Addr"  \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::PostMovePhysicsStateNotZero\")")
#define vehicleBaseObject_PostMovePhysicsStateZero_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_PostMovePhysicsStateZero_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::PostMovePhysicsStateZero\")")
#define vehicleBaseObject_PreUpdatePreMovePhysicsStateNotZero_Addr                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_PreUpdatePreMovePhysicsStateNotZero_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::PreUpdatePreMovePhysicsStateNotZero\")")
#define vehicleBaseObject_PreUpdatePreMovePhysicsStateZero_Addr                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_PreUpdatePreMovePhysicsStateZero_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::PreUpdatePreMovePhysicsStateZero\")")
#define vehicleBaseObject_Reset8B4_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_Reset8B4_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::Reset8B4\")")
#define vehicleBaseObject_SetPhysicsState_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_SetPhysicsState_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::SetPhysicsState\")")
#define vehicleBaseObject_UnsetPhysicsStates_Addr 0x258453C
#define vehicleBaseObject_UpdatePhysicsSleepState_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBaseObject_UpdatePhysicsSleepState_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BaseObject::UpdatePhysicsSleepState\")")
#define vehicleBikeBaseObject_EnableTiltControl_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleBikeBaseObject_EnableTiltControl_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::BikeBaseObject::EnableTiltControl\")")
#define vehicleBikePhysics_AnimationUpdate_Addr 0x40A4F0
#define vehicleBikePhysics_VFT_Addr 0x2AEA968
#define vehicleCameraManager_ChangeCamera_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCameraManager_ChangeCamera_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::CameraManager::ChangeCamera\")")
#define vehicleCameraManager_IsTPP_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCameraManager_IsTPP_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::CameraManager::IsTPP\")")
#define vehicleCameraManager_ShouldUseSomeListener_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCameraManager_ShouldUseSomeListener_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::CameraManager::ShouldUseSomeListener\")")
#define vehicleCameraManager_Update_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCameraManager_Update_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::CameraManager::Update\")")
#define vehicleCarPhysics_AnimationUpdate_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCarPhysics_AnimationUpdate_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::CarPhysics::AnimationUpdate\")")
#define vehicleCarPhysics_VFT_Addr 0x3061F60
#define vehicleChassisComponent_BigUpdate_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_BigUpdate_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::BigUpdate\")")
#define vehicleChassisComponent_GetCollisionShapes_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_GetCollisionShapes_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::GetCollisionShapes\")")
#define vehicleChassisComponent_SetDampingToPoint4_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_SetDampingToPoint4_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::SetDampingToPoint4\")")
#define vehicleChassisComponent_SetFilterData_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_SetFilterData_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::SetFilterData\")")
#define vehicleChassisComponent_SomethingIfEnabled_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_SomethingIfEnabled_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::SomethingIfEnabled\")")
#define vehicleChassisComponent_TransformWorldTransform_Addr                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_TransformWorldTransform_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::TransformWorldTransform\")")
#define vehicleChassisComponent_Unknown1_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_Unknown1_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::Unknown1\")")
#define vehicleChassisComponent_Update_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_Update_Addr"                 \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::Update\")")
#define vehicleChassisComponent_UpdatePhysicsState_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_UpdatePhysicsState_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::UpdatePhysicsState\")")
#define vehicleCollisions_CopyOverCollisionForce_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCollisions_CopyOverCollisionForce_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Collisions::CopyOverCollisionForce\")")
#define vehicleCollisions_SetAcceleration_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCollisions_SetAcceleration_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Collisions::SetAcceleration\")")
#define vehicleCollisions_SetLinearVelocityEtc_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCollisions_SetLinearVelocityEtc_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Collisions::SetLinearVelocityEtc\")")
#define vehicleCollisions_SetUnkD0_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCollisions_SetUnkD0_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Collisions::SetUnkD0\")")
#define vehicleEffects_GetCollisionFxForMaterial_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleEffects_GetCollisionFxForMaterial_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Effects::GetCollisionFxForMaterial\")")
#define vehicleEffects_GetSmearFxForMaterial_Addr 0xC23AFC
#define vehicleEffects_ProcessEffects_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleEffects_ProcessEffects_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Effects::ProcessEffects\")")
#define vehicleEffects_ProcessImpactScratch_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleEffects_ProcessImpactScratch_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Effects::ProcessImpactScratch\")")
#define vehicleEffects_Setup_Addr                                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleEffects_Setup_Addr"                           \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Effects::Setup\")")
#define vehicleEffects_UpdateEffectsBlackboard_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleEffects_UpdateEffectsBlackboard_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Effects::UpdateEffectsBlackboard\")")
#define vehicleEffects_WheelEffectUpdate_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleEffects_WheelEffectUpdate_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Effects::WheelEffectUpdate\")")
#define vehiclePID_GetCorrection_Addr                                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePID_GetCorrection_Addr"                       \
              "is 0 - Zoltan found too many matches for RED4ext::vehicle::PID::GetCorrection (4)\")")
#define vehiclePID_Initialize_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePID_Initialize_Addr"                          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PID::Initialize\")")
#define vehiclePID_Process_Addr                                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePID_Process_Addr"                             \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PID::Process\")")
#define vehiclePID_Reset_Addr                                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePID_Reset_Addr"                               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PID::Reset\")")
#define vehiclePID_UpdatePID_Addr                                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePID_UpdatePID_Addr"                           \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PID::UpdatePID\")")
#define vehiclePersistentDataPS_ResetQuestEnforceTransform_Addr                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePersistentDataPS_ResetQuestEnforceTransform_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PersistentDataPS::ResetQuestEnforceTransform\")")
#define vehiclePersistentDataPS_UpdateWheelRuntime_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePersistentDataPS_UpdateWheelRuntime_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PersistentDataPS::UpdateWheelRuntime\")")
#define vehiclePhysicsData_AddTorque_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysicsData_AddTorque_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PhysicsData::AddTorque\")")
#define vehiclePhysicsData_ApplyForceAtPosition_Addr 0x2355B0
#define vehiclePhysicsData_ApplyForceTorque_Addr 0x23546C
#define vehiclePhysicsData_ApplyTorqueAtPosition_Addr 0x34DEC4
#define vehiclePhysicsData_SetUsesNormalChassisMass_Addr                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysicsData_SetUsesNormalChassisMass_Addr"    \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PhysicsData::SetUsesNormalChassisMass\")")
#define vehiclePhysicsData_UpdateChassis_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysicsData_UpdateChassis_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PhysicsData::UpdateChassis\")")
#define vehiclePhysicsData_UsesAlternativeChassisMass_Addr                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysicsData_UsesAlternativeChassisMass_Addr"  \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PhysicsData::UsesAlternativeChassisMass\")")
#define vehiclePhysics_ComputeSleep_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysics_ComputeSleep_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Physics::ComputeSleep\")")
#define vehiclePhysics_GetSomethingWaterParams_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysics_GetSomethingWaterParams_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Physics::GetSomethingWaterParams\")")
#define vehiclePhysics_GetVehicle_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysics_GetVehicle_Addr"                      \
              "is 0 - Zoltan found too many matches for RED4ext::vehicle::Physics::GetVehicle (2)\")")
#define vehiclePhysics_IsInAirFromVehicle_func_Addr                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysics_IsInAirFromVehicle_func_Addr"         \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Physics::IsInAirFromVehicle_func\")")
#define vehiclePhysics_LoadHasBeenFlippedOver_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysics_LoadHasBeenFlippedOver_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Physics::LoadHasBeenFlippedOver\")")
#define vehiclePhysics_ReadWorldTransform_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysics_ReadWorldTransform_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Physics::ReadWorldTransform\")")
#define vehiclePhysics_SetUnkA0ToOne_Addr 0xFF8076
#define vehiclePhysics_UpdateDataWorldTransform_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePhysics_UpdateDataWorldTransform_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Physics::UpdateDataWorldTransform\")")
#define vehiclePhysics_VFT_Addr 0x2AEB890
#define vehicleTPPCameraComponent_GetLocationFromOffset_Addr                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_GetLocationFromOffset_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::GetLocationFromOffset\")")
#define vehicleTPPCameraComponent_GetYaw_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_GetYaw_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::GetYaw\")")
#define vehicleTPPCameraComponent_TargetedCameraInterface_Update_Addr                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_TargetedCameraInterface_Update_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::TargetedCameraInterface_Update\")")
#define vehicleTPPCameraComponent_TargetedCameraInterface_sub_58_Addr                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_TargetedCameraInterface_sub_58_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::TargetedCameraInterface_sub_58\")")
#define vehicleTPPCameraComponent_UpdateData_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_UpdateData_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::UpdateData\")")
#define vehicleTPPCameraComponent_UpdatePitch_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_UpdatePitch_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::UpdatePitch\")")
#define vehicleTPPCameraComponent_UpdatePosition_Addr                                                                  \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_UpdatePosition_Addr"       \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::UpdatePosition\")")
#define vehicleTPPCameraComponent_UpdateTPP_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_UpdateTPP_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::UpdateTPP\")")
#define vehicleTankPhysics_VFT_Addr 0x2C5F6B8
#define vehicleUnk588_Unknown_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleUnk588_Unknown_Addr"                          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Unk588::Unknown\")")
#define vehicleUnk588_UpdateTransform_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleUnk588_UpdateTransform_Addr"                  \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Unk588::UpdateTransform\")")
#define vehicleUnkD10_Reset_Addr 0xB3AE18
#define vehicleWheeledPhysics_ApplyWaterResistance_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_ApplyWaterResistance_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::ApplyWaterResistance\")")
#define vehicleWheeledPhysics_FixedUpdate_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_FixedUpdate_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::FixedUpdate\")")
#define vehicleWheeledPhysics_FourWheelTorque_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_FourWheelTorque_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::FourWheelTorque\")")
#define vehicleWheeledPhysics_FourWheelTorqueStuff_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_FourWheelTorqueStuff_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::FourWheelTorqueStuff\")")
#define vehicleWheeledPhysics_GetEnergy_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_GetEnergy_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::GetEnergy\")")
#define vehicleWheeledPhysics_GetNumberOfWheelsTouchingGround_Addr                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_GetNumberOfWheelsTouchingGround_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::GetNumberOfWheelsTouchingGround\")")
#define vehicleWheeledPhysics_ProcessAirControl_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_ProcessAirControl_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::ProcessAirControl\")")
#define vehicleWheeledPhysics_SetIsMovingOthers_Addr                                                                   \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_SetIsMovingOthers_Addr"        \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::SetIsMovingOthers\")")
#define vehicleWheeledPhysics_SetupInsert_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_SetupInsert_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::SetupInsert\")")
#define vehicleWheeledPhysics_SomethingWheelRayTrace_Addr                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_SomethingWheelRayTrace_Addr"   \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::SomethingWheelRayTrace\")")
#define vehicleWheeledPhysics_SomethingWheels_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_SomethingWheels_Addr"          \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::SomethingWheels\")")
#define vehicleWheeledPhysics_TurningRollFactorStuff_Addr                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_TurningRollFactorStuff_Addr"   \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::TurningRollFactorStuff\")")
#define vehicleWheeledPhysics_Unk15CStuff_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_Unk15CStuff_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::Unk15CStuff\")")
#define vehicleWheeledPhysics_Update_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_Update_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::Update\")")
#define vehicleWheeledPhysics_UpdatePassengerAnim_Addr                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleWheeledPhysics_UpdatePassengerAnim_Addr"      \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::WheeledPhysics::UpdatePassengerAnim\")")
#define vehicleWheeledPhysics_VFT_Addr 0x2AEB6D8
#define worldEffectBlackboard_SetValue_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: worldEffectBlackboard_SetValue_Addr"                 \
              "is 0 - Zoltan found no matches for RED4ext::world::EffectBlackboard::SetValue\")")
#define worldRuntimeScene_SetupWithLogging_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: worldRuntimeScene_SetupWithLogging_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::world::RuntimeScene::SetupWithLogging\")")
#define worldRuntimeSystemPhysics_FreeGeos_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: worldRuntimeSystemPhysics_FreeGeos_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::world::RuntimeSystemPhysics::FreeGeos\")")
