#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/Generated/WorldTransform.hpp>
#include <RED4ext/Scripting/Natives/Generated/Transform.hpp>

namespace RED4ext::ent {

struct ITransformAttachable {

    /// @hash 3227782038:idata
    static constexpr const uintptr_t VFT = entITransformAttachable_VFT_Addr;

    virtual ~ITransformAttachable() = default;
    // called from OnSimulate_PushDirtyTransformData when flags & 0x40 or unk38 == 2
    // WT & bool comes from unk1A2018 - Transform is empty
    virtual void ITransformAttachable_08(WorldTransform *, bool, Transform*) {};
    // empty for many implementations
    // called with idStorage.unk00, unk24 and unk28 from Physics/KickAndWaitSimulation/NotifyListeners
    virtual void ITransformAttachable_10(uint64_t, uint32_t, uint32_t) {};
};

}