#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/NativeTypes.hpp>
#include <RED4ext/Scripting/Natives/Generated/WorldTransform.hpp>

namespace RED4ext::vehicle
{

struct BaseObject;

struct PartData
{
  CName name;
  Handle<ent::IComponent> attachedComponents[16];
  uint32_t numAttachedComponents;
  uint32_t unk10C;
  Handle<ent::IComponent> detachedComponents[16];
  uint32_t numDetachedComponents;
  uint32_t unk214;
  uint8_t unk218[16]; // 255, 5, 5
  uint32_t unk228; // 2
  uint32_t unk22C;
  uint64_t unk230;
  uint64_t unk238;
  uint8_t unk240;
  uint64_t effectToken[2];
};

struct Manager {
  vehicle::BaseObject *vehicle;
  uint8_t spawn_set[0x48];
  uint64_t unk50;
  uint64_t unk58;
  uint64_t unk60;
  uint64_t unk68;
  DynArray<void*> unk70;
  DynArray<PartData> parts;
  HashMap<CName, uint32_t> unk90;
  uint64_t detachedPartExplosionEffect;
  uint32_t unkC8;
  uint32_t unkCC;
};

struct Destruction
{
    Handle<void> unk00;
    Manager manager;
};
// RED4EXT_ASSERT_SIZE(Destruction, 0x600);

}